features:
  alpha: 0.02

split:
  train: 0.70
  val: 0.15
  test: 0.15

model:
  type: "mlp"   # "mlp" or "svm"

  mlp:
    epochs: 400
    batch_size: 512
    lr: 1e-3
    experiment_name: "test"

    scheduler:
      step: 200        # la cate epoci se modifica LR
      factor: 0.1    # lr = lr * factor

  svm:
    C: 10.0
    kernel: "rbf"
    gamma: "scale"
